import type { BookingSummary, Connection } from './types';

/**
 * Deliberately local fixtures for the isolated interface milestone.
 * These are examples only and must be replaced by the host application's contracts.
 * Fingerprints and action ids are fictional and never refer to real executions.
 */
export const DEMO_BOOKINGS: BookingSummary[] = [
  {
    id: 'booking-clara-01',
    clientName: 'Clara & James',
    eventType: 'Wedding dinner',
    eventDate: 'Sat, 18 Oct',
    eventTime: '6:30 – 11:00 pm',
    guestCount: 84,
    venue: 'The Glasshouse',
    budget: '$14,600',
    status: 'needs-review',
    statusLabel: 'Needs your review',
    nextAction: 'Review the dinner proposal',
    clientInitials: 'CJ',
    clientTone: 'coral',
    detail: {
      receivedAt: 'Today at 9:18 am',
      source: 'Gmail · Clara & James',
      requestSummary:
        'An intimate autumn wedding dinner with a family-style menu, welcome cocktails, and a late-night dessert table.',
      packageName: 'Garden dinner · family style',
      packageDescription: 'Seasonal menu, welcome drinks, and evening service for 84 guests.',
      proposal: {
        id: 'demo-action-clara-v2',
        version: 2,
        versionLabel: 'Version 2 · prepared today',
        fingerprint: 'demo-fp-clara-v2-9f2c',
        total: '$14,600',
        deposit: '$4,380 deposit',
        validUntil: 'Hold valid until 24 Sep',
        consequences: [
          'Re-check calendar availability for Sat, 18 Oct · 6:30 – 11:00 pm',
          'Create a provisional hold that expires 24 Sep — not a confirmed booking',
          'Send the offer email to Clara & James',
        ],
        lines: [
          { label: 'Dinner package', detail: '84 guests · family style', amount: '$9,240' },
          { label: 'Welcome cocktails', detail: '90 minutes · passed service', amount: '$1,680' },
          { label: 'Dessert table', detail: 'Seasonal fruit & petit fours', amount: '$1,260' },
          { label: 'Staffing & setup', detail: 'Event lead plus four servers', amount: '$2,420' },
        ],
        sources: [
          { title: 'Autumn menus 2025', detail: 'Google Drive · updated 03 Sep', kind: 'drive' },
          { title: 'Saturday availability', detail: 'Google Calendar · 18 Oct', kind: 'calendar' },
          { title: 'Clara & James inquiry', detail: 'Gmail · 3 messages', kind: 'email' },
        ],
      },
      activity: [
        { id: 'clara-inquiry', label: 'Inquiry received', detail: 'Email from Clara & James', timestamp: '9:18 am', kind: 'inquiry' },
        { id: 'clara-sources', label: 'Business context gathered', detail: 'Menu, policies, and availability checked', timestamp: '9:23 am', kind: 'source' },
        { id: 'clara-proposal', label: 'Proposal ready for review', detail: 'Version 2 · $14,600 total', timestamp: '9:25 am', kind: 'proposal' },
      ],
      receipts: [],
    },
  },
  {
    id: 'booking-maya-02',
    clientName: 'Maya Chen',
    eventType: 'Product launch',
    eventDate: 'Thu, 23 Oct',
    eventTime: '5:00 – 9:30 pm',
    guestCount: 56,
    venue: 'The Glasshouse',
    budget: '$8,900',
    status: 'waiting',
    statusLabel: 'Approval in progress',
    nextAction: 'Waiting for the approval outcome',
    clientInitials: 'MC',
    clientTone: 'blue',
    detail: {
      receivedAt: 'Yesterday at 4:06 pm',
      source: 'Gmail · Maya Chen',
      requestSummary: 'A bright, relaxed product launch with roaming canapés, a short toast, and a non-alcoholic pairing menu.',
      packageName: 'Launch evening · roaming',
      packageDescription: 'Canapés, pairings, staffing, and a simple welcome moment for 56 guests.',
      proposal: {
        id: 'demo-action-maya-v1',
        version: 1,
        versionLabel: 'Version 1 · prepared yesterday',
        fingerprint: 'demo-fp-maya-v1-41bd',
        total: '$8,900',
        deposit: '$2,670 deposit',
        validUntil: 'Hold valid until 28 Sep',
        consequences: [
          'Re-check calendar availability for Thu, 23 Oct · 5:00 – 9:30 pm',
          'Create a provisional hold that expires 28 Sep — not a confirmed booking',
          'Send the offer email to Maya Chen',
        ],
        lines: [
          { label: 'Roaming canapés', detail: '56 guests · 6 varieties', amount: '$4,480' },
          { label: 'Pairing menu', detail: 'Zero-proof · 4 pours', amount: '$1,120' },
          { label: 'Toast service', detail: 'Sparkling welcome · 30 minutes', amount: '$620' },
          { label: 'Staffing & setup', detail: 'Event lead plus two servers', amount: '$2,680' },
        ],
        sources: [
          { title: 'Launch packages', detail: 'Google Drive · updated 28 Aug', kind: 'drive' },
          { title: 'Thursday availability', detail: 'Google Calendar · 23 Oct', kind: 'calendar' },
          { title: 'Maya Chen inquiry', detail: 'Gmail · 5 messages', kind: 'email' },
        ],
      },
      activity: [
        { id: 'maya-inquiry', label: 'Inquiry received', detail: 'Email from Maya Chen', timestamp: 'Yesterday', kind: 'inquiry' },
        { id: 'maya-sources', label: 'Business context gathered', detail: 'Launch package and availability checked', timestamp: 'Yesterday', kind: 'source' },
        { id: 'maya-proposal', label: 'Proposal ready for review', detail: 'Version 1 · $8,900 total', timestamp: 'Yesterday', kind: 'proposal' },
        { id: 'maya-approval', label: 'Approval request sent', detail: 'Version 1 · awaiting the host outcome', timestamp: '10:02 am', kind: 'proposal' },
      ],
      receipts: [
        {
          id: 'demo-receipt-maya-approval',
          actionId: 'demo-action-maya-v1',
          label: 'Approval request',
          detail: 'Sent to the approval service — the outcome is not known yet.',
          status: 'pending',
          timestamp: '10:02 am',
        },
      ],
    },
  },
  {
    id: 'booking-owen-03',
    clientName: 'Owen & Co.',
    eventType: 'Team supper',
    eventDate: 'Fri, 31 Oct',
    eventTime: '7:00 – 10:00 pm',
    guestCount: 32,
    venue: 'The Glasshouse',
    budget: '$4,960',
    status: 'waiting',
    statusLabel: 'Waiting on connection',
    nextAction: 'Reconnect Calendar to continue',
    clientInitials: 'OC',
    clientTone: 'sage',
    detail: {
      receivedAt: 'Monday at 11:42 am',
      source: 'Gmail · Owen & Co.',
      requestSummary: 'A private team supper with a seasonal three-course menu and a quieter room for conversation.',
      packageName: 'Private supper · three course',
      packageDescription: 'Three courses, non-alcoholic pairings, and a dedicated event lead for 32 guests.',
      proposal: {
        id: 'demo-action-owen-v1',
        version: 1,
        versionLabel: 'Version 1 · prepared Monday',
        fingerprint: 'demo-fp-owen-v1-77e0',
        total: '$4,960',
        deposit: '$1,488 deposit',
        validUntil: 'Hold valid until 01 Oct',
        consequences: [
          'Re-check calendar availability for Fri, 31 Oct · 7:00 – 10:00 pm',
          'Create a provisional hold that expires 01 Oct — not a confirmed booking',
          'Send the offer email to Owen & Co.',
        ],
        lines: [
          { label: 'Three-course supper', detail: '32 guests · seasonal menu', amount: '$3,200' },
          { label: 'Pairing menu', detail: 'Zero-proof · 3 pours', amount: '$640' },
          { label: 'Private room service', detail: 'Dedicated event lead', amount: '$1,120' },
        ],
        sources: [
          { title: 'Private dining policies', detail: 'Google Drive · updated 14 Aug', kind: 'drive' },
          { title: 'Friday availability', detail: 'Google Calendar · reconnect needed', kind: 'calendar' },
          { title: 'Owen & Co. inquiry', detail: 'Gmail · 2 messages', kind: 'email' },
        ],
      },
      activity: [
        { id: 'owen-inquiry', label: 'Inquiry received', detail: 'Email from Owen & Co.', timestamp: 'Mon, 11:42 am', kind: 'inquiry' },
        { id: 'owen-warning', label: 'Availability check paused', detail: 'Calendar connection needs attention', timestamp: 'Mon, 11:47 am', kind: 'warning' },
      ],
      waitingReason: {
        title: 'Availability check is paused',
        description: 'The Google Calendar connection expired, so Gather cannot verify Fri, 31 Oct yet. Reconnect it before approving — the date will be rechecked before any hold is created.',
        actionLabel: 'Retry availability check',
        connectionsRelated: true,
      },
      receipts: [
        {
          id: 'demo-receipt-owen-availability',
          actionId: 'demo-action-owen-availability',
          executionId: 'demo-exec-owen-availability-1',
          label: 'Availability check',
          detail: 'Failed — the Calendar connection was revoked before the check ran.',
          status: 'failed',
          timestamp: 'Mon, 11:47 am',
          recoveryLabel: 'Retry availability check',
        },
      ],
    },
  },
  {
    id: 'booking-priya-04',
    clientName: 'Priya Nair',
    eventType: 'Anniversary dinner',
    eventDate: 'Sat, 08 Nov',
    eventTime: '7:30 – 11:30 pm',
    guestCount: 24,
    venue: 'The Glasshouse',
    budget: '$6,200',
    status: 'provisional-hold',
    statusLabel: 'Provisional hold',
    nextAction: 'Reconcile the offer email before treating this as sent',
    clientInitials: 'PN',
    clientTone: 'plum',
    detail: {
      receivedAt: 'Tuesday at 2:15 pm',
      source: 'Gmail · Priya Nair',
      requestSummary: 'A golden-hour anniversary dinner with a tasting menu, paired wines, and a small toast for the family.',
      packageName: 'Anniversary tasting · paired',
      packageDescription: 'Tasting menu, wine pairings, and a dedicated event lead for 24 guests.',
      proposal: {
        id: 'demo-action-priya-v3',
        version: 3,
        versionLabel: 'Version 3 · prepared Tuesday',
        fingerprint: 'demo-fp-priya-v3-b5a1',
        total: '$6,200',
        deposit: '$1,860 deposit',
        validUntil: 'Hold expires 15 Oct',
        consequences: [
          'Re-check calendar availability for Sat, 08 Nov · 7:30 – 11:30 pm',
          'Create a provisional hold that expires 15 Oct — not a confirmed booking',
          'Send the offer email to Priya Nair',
        ],
        lines: [
          { label: 'Tasting menu', detail: '24 guests · five courses', amount: '$3,600' },
          { label: 'Wine pairings', detail: 'Five pours · sommelier selected', amount: '$1,440' },
          { label: 'Staffing & setup', detail: 'Event lead plus two servers', amount: '$1,160' },
        ],
        sources: [
          { title: 'Tasting menus 2025', detail: 'Google Drive · updated 21 Aug', kind: 'drive' },
          { title: 'Saturday availability', detail: 'Google Calendar · 08 Nov', kind: 'calendar' },
          { title: 'Priya Nair inquiry', detail: 'Gmail · 4 messages', kind: 'email' },
        ],
      },
      activity: [
        { id: 'priya-inquiry', label: 'Inquiry received', detail: 'Email from Priya Nair', timestamp: 'Tue, 2:15 pm', kind: 'inquiry' },
        { id: 'priya-proposal', label: 'Proposal approved', detail: 'Version 3 · $6,200 total', timestamp: 'Tue, 4:40 pm', kind: 'proposal' },
        { id: 'priya-hold', label: 'Provisional hold created', detail: 'Expires 15 Oct — not yet confirmed', timestamp: 'Tue, 4:41 pm', kind: 'source' },
        { id: 'priya-warning', label: 'Offer email outcome unknown', detail: 'The send timed out after the request reached the provider', timestamp: 'Tue, 4:42 pm', kind: 'warning' },
      ],
      receipts: [
        {
          id: 'demo-receipt-priya-hold',
          actionId: 'demo-action-priya-v3',
          executionId: 'demo-exec-priya-hold-1',
          label: 'Provisional hold',
          detail: 'Hold created for Sat, 08 Nov · expires 15 Oct. This is not a confirmed booking.',
          status: 'succeeded',
          timestamp: 'Tue, 4:41 pm',
        },
        {
          id: 'demo-receipt-priya-offer',
          actionId: 'demo-action-priya-v3',
          executionId: 'demo-exec-priya-offer-1',
          label: 'Offer email',
          detail: 'Uncertain — the provider timed out after the request may have been sent. Reconcile before retrying.',
          status: 'uncertain',
          timestamp: 'Tue, 4:42 pm',
          recoveryLabel: 'Reconcile offer email',
        },
        {
          id: 'demo-receipt-priya-summary',
          actionId: 'demo-action-priya-v3',
          executionId: 'demo-exec-priya-summary-1',
          label: 'Owner summary card',
          detail: 'Partial — the calendar note was written but the summary email copy failed. Reconcile the execution before retrying anything.',
          status: 'partial',
          timestamp: 'Tue, 4:43 pm',
          recoveryLabel: 'Check what completed',
        },
      ],
    },
  },
  {
    id: 'booking-noor-05',
    clientName: 'Noor & Eli',
    eventType: 'Corporate tasting',
    eventDate: 'Wed, 12 Nov',
    eventTime: '12:00 – 3:00 pm',
    guestCount: 18,
    venue: 'The Glasshouse',
    budget: '$3,400',
    status: 'failed',
    statusLabel: 'Hold attempt failed',
    nextAction: 'Retry the provisional hold',
    clientInitials: 'NE',
    clientTone: 'coral',
    detail: {
      receivedAt: 'Wednesday at 10:05 am',
      source: 'Gmail · Noor & Eli',
      requestSummary: 'A midday corporate tasting with a short seasonal menu and a quiet table for the leadership team.',
      packageName: 'Midday tasting · seasonal',
      packageDescription: 'Seasonal tasting menu and a dedicated event lead for 18 guests.',
      proposal: {
        id: 'demo-action-noor-v1',
        version: 1,
        versionLabel: 'Version 1 · prepared Wednesday',
        fingerprint: 'demo-fp-noor-v1-c219',
        total: '$3,400',
        deposit: '$1,020 deposit',
        validUntil: 'Hold valid until 20 Oct',
        consequences: [
          'Re-check calendar availability for Wed, 12 Nov · 12:00 – 3:00 pm',
          'Create a provisional hold that expires 20 Oct — not a confirmed booking',
          'Send the offer email to Noor & Eli',
        ],
        lines: [
          { label: 'Seasonal tasting', detail: '18 guests · three courses', amount: '$2,160' },
          { label: 'Staffing & setup', detail: 'Event lead plus one server', amount: '$1,240' },
        ],
        sources: [
          { title: 'Corporate packages', detail: 'Google Drive · updated 05 Sep', kind: 'drive' },
          { title: 'Wednesday availability', detail: 'Google Calendar · 12 Nov', kind: 'calendar' },
          { title: 'Noor & Eli inquiry', detail: 'Gmail · 2 messages', kind: 'email' },
        ],
      },
      activity: [
        { id: 'noor-inquiry', label: 'Inquiry received', detail: 'Email from Noor & Eli', timestamp: 'Wed, 10:05 am', kind: 'inquiry' },
        { id: 'noor-proposal', label: 'Proposal approved', detail: 'Version 1 · $3,400 total', timestamp: 'Wed, 11:20 am', kind: 'proposal' },
        { id: 'noor-warning', label: 'Hold attempt failed', detail: 'The slot was taken before the hold could be created', timestamp: 'Wed, 11:21 am', kind: 'warning' },
      ],
      receipts: [
        {
          id: 'demo-receipt-noor-hold',
          actionId: 'demo-action-noor-v1',
          executionId: 'demo-exec-noor-hold-1',
          label: 'Provisional hold',
          detail: 'Failed — the 12 Nov slot is no longer available. No hold was created.',
          status: 'failed',
          timestamp: 'Wed, 11:21 am',
          recoveryLabel: 'Retry provisional hold',
        },
      ],
    },
  },
];

export const DEMO_CONNECTIONS: Connection[] = [
  {
    provider: 'gmail',
    name: 'Gmail',
    description: 'Read incoming inquiries and keep the conversation in one place.',
    detail: 'Connected · gather@glasshouse.example',
    connected: true,
    lastSynced: 'Synced 4 minutes ago',
  },
  {
    provider: 'drive',
    name: 'Google Drive',
    description: 'Reference menus, packages, policies, and other business context.',
    detail: 'Connected · The Glasshouse / Gather',
    connected: true,
    lastSynced: 'Synced 12 minutes ago',
  },
  {
    provider: 'calendar',
    name: 'Google Calendar',
    description: 'Check availability before an offer is sent or a hold is created.',
    detail: 'Needs attention · permission expired',
    connected: false,
    recommended: true,
  },
];
