export {
  KnowledgeService,
  KnowledgeError,
  KnowledgeDeniedError,
  runWithBusyRetry,
  type IntakeCandidateInput,
  type CandidateView,
  type DecisionCommand,
  type ConfirmResult,
  type ResolveConflictResult,
} from "./service.ts";
export type {
  KnowledgeStorePort,
  AgreementGroup,
  BusinessConflict,
  CandidateConfidence,
  CandidateStatus,
  ConflictRevision,
  FactScope,
  KnowledgeActor,
  KnowledgeActorKind,
  KnowledgeCandidate,
  KnowledgeRevision,
  ConfirmedFact,
  KnowledgeDecision,
  DecisionKind,
  DecisionOutcome,
  OffersKnowledgeSnapshot,
  WithheldFact,
} from "./types.ts";
// ADR-005 consumers over the ADR-008 port contract (review, rules, concessions).
export {
  batchConfirmCandidates,
  correctAndPublish,
  describeAvailability,
  inspectSourceClaims,
  listCorrectionEvents,
  publishCorrectionEvent,
  type BatchConfirmInput,
  type BatchConfirmResult,
  type CorrectAndPublishInput,
  type CorrectAndPublishResult,
  type CorrectionEvent,
  type CorrectionEventInput,
  type InspectedCandidate,
  type KnowledgeAvailability,
  type ReviewStorePort,
  type SourceInspection,
} from "./review.ts";
export {
  confirmParsedRule,
  parseOwnerRuleText,
  type ConfirmParsedRuleInput,
  type ParsedRuleDraft,
  type ParsedRuleKind,
  type ParsedRuleScope,
  type ParseOwnerRuleResult,
} from "./rules.ts";
export {
  CONCESSION_APPROVAL_NOTICE,
  validateConcessionForm,
  type ConcessionFormInput,
  type ValidatedConcessionForm,
} from "./concessions.ts";
