export {
  KnowledgeService,
  KnowledgeError,
  KnowledgeDeniedError,
  runWithBusyRetry,
  type IntakeCandidateInput,
  type CandidateView,
  type DecisionCommand,
  type ConfirmResult,
  type ResolveConflictResult,
} from "./service.ts";
export type {
  KnowledgeStorePort,
  AgreementGroup,
  BusinessConflict,
  CandidateConfidence,
  CandidateStatus,
  ConflictRevision,
  FactScope,
  KnowledgeActor,
  KnowledgeActorKind,
  KnowledgeCandidate,
  KnowledgeRevision,
  ConfirmedFact,
  KnowledgeDecision,
  DecisionKind,
  DecisionOutcome,
  OffersKnowledgeSnapshot,
  WithheldFact,
} from "./types.ts";
